

###
GET http://localhost:3000/


###client point of view

### get list of products
GET http://localhost:3000/products

### get list of professionals 
GET http://localhost:3000/professionals

### get professional 
GET http://localhost:3000/professional/6

### get reviews 
GET http://localhost:3000/reviews/2


### add review
POST http://localhost:3000/reviews/add HTTP/1.1
Content-Type: application/json

{
    "professionalID": 2,
    "reviewerName": "Filan Fisteku",
    "score": 4,
    "comment": "Well done job with my sink"
}

### -------------------Professional point of view

###get orders professional

GET http://localhost:3000/orders/professionals/3

###get specific order professional
GET http://localhost:3000/orders/professionals/3/65f7195b26dd8330c12c47d3

### add order
POST http://localhost:3000/orders/add HTTP/1.1
Content-Type: application/json

{
    "professionalID":3,
    "products":[{"name":"Product 1","quantity":2},{"name":"PVC tube 3m","quantity":2}]
}

### delete order
DELETE http://localhost:3000/orders/delete/65f722096b8bb54922b1ecb4 HTTP/1.1


### modify order add remove 
PUT http://localhost:3000/orders/modify/65f723b5408704322df6fb69 HTTP/1.1
Content-Type: application/json

{
        "products":[{"name":"PVC tube 4m 30cm diameter","quantity":3},{"name":"PVC tube 3m","quantity":2}]
}

### change status 

GET http://localhost:3000/professionals/status/1 HTTP/1.1


### admin point of view

### get list of orders (only admin can complete later after authentication implementation)
GET http://localhost:3000/orders


### managment of inventory , add remove , modify product 

### Add Product
POST http://localhost:3000/products/add
Content-Type: application/json

{
    "name": "PVC",
    "category": "Hardware",
    "distributor": "Distributor A",
    "manufacturer": "Manufacturer A",
    "origin": "USA",
    "priceBought": 100,
    "priceSold": 150,
    "quantity": 10
}
### Modify Product
PUT http://localhost:3000/products/modify
Content-Type: application/json

{
    "name" : "Product 5",
    "quantity": 20
}

### delete product
DELETE http://localhost:3000/products/delete
Content-Type: application/json

{
    "name": "PVC"
}


### handle professionals 

### add professional 
POST http://localhost:3000/professionals/add HTTP/1.1
Content-Type: application/json

{
    "professionalID": 6,
    "fullName": "John Doe",
    "age": 30,
    "ShortDescription": "Experienced plumber.",
    "reviewScore": 4.5,
    "phoneNumber": "1234567890"
}

### modify professional 
PUT http://localhost:3000/professionals/modify
Content-Type: application/json

{
    "professionalID": 6,
    "fullName": "John Doe",
    "age": 35,
    "ShortDescription": "Experienced plumber with over 10 years of experience.",
    "reviewScore": 4.7,
    "phoneNumber": "1234567890"
}

### delete professional
DELETE http://localhost:3000/professionals/delete/6

### remove review of a professional
DELETE http://localhost:3000/reviews/delete/65f71054d9e86bc61a7095e4

### handle orders 

### get orders 

GET http://localhost:3000/orders

### get order 
GET http://localhost:3000/orders/65f7195b26dd8330c12c47ce

### delete order already implemented 


### accept order
PUT http://localhost:3000/orders/accept/65f85556794de74d979d8659
Content-Type: application/json

{
    "accepted": true
}

